### ISSUE TITLE
An unexpected error happened

### ISSUE THREAD

**Issue by zhuwenxing** [g1eny0ung/grafana-chaos-mesh-datasource#1]
I can visit the dashboard with url http://{node_ip}:31558. So I think the URL I write in the setting is correct. But still, get a problem!

![image](https://user-images.githubusercontent.com/12268675/110411298-4802fc80-80c5-11eb-9cfb-fe5c314673b1.png)

![image](https://user-images.githubusercontent.com/12268675/110411334-581adc00-80c5-11eb-9576-6892c9ef1dc0.png)

**Comment by g1eny0ung** [comment]
The browser console should output some errors. Can I take a look at them?

**Comment by zhuwenxing** [comment]
![image](https://user-images.githubusercontent.com/12268675/110416222-44c03e80-80ce-11eb-9f67-d2677c691feb.png)

**Comment by g1eny0ung** [comment]
I test in my local environment with `NodePort ` access and all works fine. In my current knowledge, it seems that this error will only occur if the network request fails.

I use the `/api/config` to check the connection, so I think there should have a request error in the network panel of browser dev tools.

**Comment by g1eny0ung** [comment]
I decide to archive this repo because all of the codes are migrated into https://github.com/chaos-mesh/chaos-mesh-datasource.

If you still encounter this problem, please open a new issue in the https://github.com/chaos-mesh/chaos-mesh-datasource/issues.
